cadasta/config/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

api_v1 = [
    url(r'^account/', include('accounts.urls.api', namespace='accounts')),
    url(r'^account/', include('djoser.urls.authtoken')),

    url(r'^organizations/',
        include('organization.urls.api.organizations',
                namespace='organization')),
    url(r'^projects/',
        include('organization.urls.api.projects',
                namespace='project')),
    url(r'^users/',
        include('organization.urls.api.users',
                namespace='user')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project_id>[-\w]+)/',
        include('questionnaires.urls.api',
                namespace='questionnaires')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project>[-\w]+)/',
        include('resources.urls.api',
                namespace='resources')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project>[-\w]+)/spatial/',
        include('spatial.urls.api.spatial',
                namespace='spatial')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project>[-\w]+)/parties/',
        include('party.urls.api.parties',
                namespace='party')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project>[-\w]+)/relationships/',
        include('party.urls.api.relationships',
                namespace='relationship')),
]

api = [
    url(r'^v1/', include(api_v1, namespace='v1'))
]

urlpatterns = [
    url(r'^',
        include('core.urls',
                namespace='core')),
    url(r'^account/',
        include('accounts.urls.default',
                namespace='account')),
    url(r'^account/',
        include('allauth.urls')),
    url('^',
        include('django.contrib.auth.urls')),
    url(r'^organizations/',
        include('organization.urls.default.organizations',
                namespace='organization')),
    url(r'^projects/',
        include('organization.urls.default.projects',
                namespace='project')),
    url(r'^users/',
        include('organization.urls.default.users',
                namespace='user')),
    url(r'^',
        include('party.urls.default',
                namespace='parties')),
    url(r'^',
        include('spatial.urls.default',
                namespace='locations')),
    url(r'^',
        include('resources.urls.default',
                namespace='resources')),

    url(r'^api/',
        include(api,
                namespace='api')),

    url(r'^i18n/',
        include('django.conf.urls.i18n')),

    url(r'', include('buckets.test.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadasta/core/urls.py
from django.conf.urls import url

from core.views import default

urlpatterns = [
    url(r'^$', default.IndexPage.as_view(), name='index'),
    url(r'^dashboard/$', default.Dashboard.as_view(), name='dashboard'),
]

cadasta/organization/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.OrganizationList.as_view(),
        name='list'),
    url(
        r'^(?P<slug>[-\w]+)/$',
        views.OrganizationDetail.as_view(),
        name='detail'),
    url(
        r'^(?P<slug>[-\w]+)/users/$',
        views.OrganizationUsers.as_view(),
        name='users'),
    url(
        r'^(?P<slug>[-\w]+)/users/(?P<username>[-\w]+)/$',
        views.OrganizationUsersDetail.as_view(),
        name='users_detail'),
    url(
        r'^(?P<slug>[-\w]+)/projects/$',
        views.ProjectList.as_view(),
        name='project_list'),
    url(
        r'^(?P<slug>[-\w]+)/projects/(?P<project_id>[-\w]+)/users/$',
        views.ProjectUsers.as_view(),
        name='project_users'),
    url(
        r'^(?P<slug>[-\w]+)/projects/(?P<project_id>[-\w]+)/users/(?P<username>[-\w]+)/$',
        views.ProjectUsersDetail.as_view(),
        name='project_users_detail'),
]

cadasta/core/models.py
import itertools
import math
from core.util import slugify
from django.db import models
from django.utils.functional import cached_property

from .util import random_id, ID_FIELD_LENGTH


class RandomIDModel(models.Model):
    id = models.CharField(primary_key=True, max_length=ID_FIELD_LENGTH)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.id:
            kwargs['force_insert'] = True

            ok = False
            while not ok:
                self.id = random_id()

                if not type(self).objects.filter(pk=self.id).exists():
                    ok = True
                    super(RandomIDModel, self).save(*args, **kwargs)

        else:
            super(RandomIDModel, self).save(*args, **kwargs)


class SlugModel:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_slug = self.slug

    def save(self, *args, **kwargs):
        max_length = self._meta.get_field('slug').max_length
        if not self.slug:
            self.slug = slugify(
                self.name, max_length=max_length, allow_unicode=True
            )

        orig_slug = self.slug

        if not self.id or self.__original_slug != self.slug:
            for x in itertools.count(1):
                if not type(self).objects.filter(slug=self.slug).exists():
                    break
                slug_length = max_length - int(math.log10(x)) - 2
                trial_slug = orig_slug[:slug_length]
                self.slug = '{}-{}'.format(trial_slug, x)

        self.__original_slug = self.slug

        return super().save(*args, **kwargs)


class Role(RandomIDModel):
    class Meta:
        abstract = True

    user = models.ForeignKey('accounts.User')

    @cached_property
    def permissions(self):
        return self.group.permissions.values_list('codename', flat=True)

cadasta/core/views.py
import json
import re
from django.http import Http404
from django.utils import six
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework.exceptions import NotFound
from rest_framework.views import exception_handler as drf_exception_handler


def set_exception(exception):
    if (type(exception) is Http404):
        exception_msg = str(exception)
        try:
            model = re.search(
                'No (.+?) matches the given query.', exception_msg).group(1)
            exception = NotFound(_("{name} not found.").format(name=model))
        except AttributeError:
            pass
    return exception


def eval_json(response_data):
    """
    Evaluate stringified JSON objects, so we can return structure
    error responses
    """
    for key in response_data:
        errors = []
        if not isinstance(response_data[key], six.string_types):
            for e in response_data[key]:
                try:
                    errors.append(json.loads(e))
                except ValueError:
                    errors.append(e)
            response_data[key] = errors

    return response_data


def exception_handler(exception, context):
    """
    Overwriting Django Rest Frameworks exception handler to provide more
    meaniful exception messages for 404 errors.
    """
    exception = set_exception(exception)

    response = drf_exception_handler(exception, context)

    if response:
        response.data = eval_json(response.data)

        return response


class IndexPage(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_anonymous():
            return redirect('core:dashboard')

        return super(IndexPage, self).get(request, *args, **kwargs)


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

cadasta/core/views/api.py
import logging
import json
import re
from django.http import Http404
from django.utils import six
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError as DjangoValidationError

from rest_framework.exceptions import NotFound
from rest_framework.exceptions import ValidationError as DRFValidationError
from rest_framework.views import exception_handler as drf_exception_handler

logger = logging.getLogger('core')


def set_exception(exception, url):
    if isinstance(exception, Http404):
        exception_msg = str(exception)
        try:
            model = re.search(
                'No (.+?) matches the given query.', exception_msg).group(1)
            exception = NotFound(_("{name} not found.").format(name=model))
        except AttributeError:
            pass

    elif isinstance(exception, DjangoValidationError):
        if hasattr(exception, 'message_dict'):
            detail = exception.message_dict
        elif hasattr(exception, 'message'):
            detail = {'detail': exception.message}
        elif hasattr(exception, 'messages'):
            detail = {'detail': exception.messages}

        logger.exception(
            "ValidationError raised at {}: {}".format(url, exception))

        exception = DRFValidationError(detail=detail)

    return exception


def eval_json(response_data):
    """
    Evaluate stringified JSON objects, so we can return structured
    error responses
    """
    if not isinstance(response_data, dict):
        return response_data

    for key in response_data:
        errors = []
        if not isinstance(response_data[key], six.string_types):
            for e in response_data[key]:
                try:
                    errors.append(json.loads(e))
                except (ValueError, TypeError):
                    errors.append(e)
            response_data[key] = errors

    return response_data


def exception_handler(exception, context):
    """
    Overwriting Django Rest Frameworks exception handler to provide more
    meaningful exception messages for 404 and validation errors.
    """
    exception = set_exception(exception,
                              context['request'].build_absolute_uri())
    response = drf_exception_handler(exception, context)

    if response:
        response.data = eval_json(response.data)

        return response

cadasta/core/views/default.py
import json

from django.db.models import Q
from django.shortcuts import redirect

from core.views.generic import TemplateView
from organization.models import Project
from organization.serializers import ProjectGeometrySerializer


class IndexPage(TemplateView):
    template_name = 'core/index.html'

    def get(self, request, *args, **kwargs):
        return redirect('core:dashboard')


class Dashboard(TemplateView):
    template_name = 'core/dashboard.html'

    def get_context_data(self, projects, **kwargs):
        context = super().get_context_data(**kwargs)
        context['geojson'] = json.dumps(
            ProjectGeometrySerializer(projects, many=True).data
        )
        return context

    def get(self, request, *args, **kwargs):
        projects = Project.objects.filter(extent__isnull=False)
        if not self.is_superuser:
            query = Q(access='public')

            if self.request.user.is_authenticated:
                query |= Q(
                    organization__organizationrole__user=self.request.user,
                    access='private')
            projects = projects.filter(query)
            projects = projects.filter(archived=False)
        projects = projects.select_related('organization').distinct()
        context = self.get_context_data(projects=projects)
        return super(TemplateView, self).render_to_response(context)


def server_error(request, template_name='500.html'):
    """
    500 error handler.

    Templates: `500.html`
    Context: None
    """
    from django.template import loader
    from django.http import HttpResponseServerError
    t = loader.get_template(template_name)
    return HttpResponseServerError(t.render())

cadasta/core/views/generic.py
import django.views.generic as base

from .mixins import SuperUserCheckMixin


class TemplateView(SuperUserCheckMixin, base.TemplateView):
    pass


class ListView(SuperUserCheckMixin, base.ListView):
    pass


class DetailView(SuperUserCheckMixin, base.DetailView):
    pass


class CreateView(SuperUserCheckMixin, base.CreateView):
    pass


class UpdateView(SuperUserCheckMixin, base.UpdateView):
    pass


class DeleteView(SuperUserCheckMixin, base.DeleteView):
    pass

cadasta/core/views/mixins.py
from django.shortcuts import redirect
from django.db.models import Q


class ArchiveMixin:
    def archive(self):
        assert hasattr(self, 'do_archive'), "Please set do_archive attribute"
        self.object = self.get_object()
        self.object.archived = self.do_archive
        self.object.save()

        return redirect(self.get_success_url())

    def get(self, request, *args, **kwargs):
        return self.archive()


class SuperUserCheckMixin:
    @property
    def is_superuser(self):
        return self.request.user.is_superuser

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['is_superuser'] = self.is_superuser
        return context


class AsyncList:
    def build_search_query(self, term):
        raise NotImplementedError(
            "You need to implement the method build_search_query.")

    def get_results(self):
        assert hasattr(self, 'sort_columns'), ("Attribute sort_columns is not "
                                               "defined for the view.")

        query = self.request.GET
        qs = self.get_queryset()

        records_total = qs.count()
        # filter the queryset if a search term was provided
        search_term = query.get('search[value]')

        if search_term:
            search = self.build_search_query(search_term)
            assert isinstance(search, Q), ("Return value of build_search_query"
                                           " must be instance of "
                                           "django.db.models.Q")
            qs = qs.filter(search)
        records_filtered = qs.count()

        # set the ordering for the queryset
        order_col = int(query.get('order[0][column]', 0))
        order_dir = '' if query.get('order[0][dir]', 'asc') == 'asc' else '-'
        qs = qs.order_by(order_dir + self.sort_columns[order_col])

        # Slice the queryset to results for the current page
        offset = int(query.get('start', 0))
        limit = int(query.get('length', 10)) + offset
        qs = qs[offset:limit]

        return qs, records_total, records_filtered


class CacheObjectMixin:
    def get_object(self):
        if not hasattr(self, '_object'):
            self._object = super().get_object()
        return self._object

cadasta/templates/core/base.html
{% load i18n %}
{% load sass_tags %}
{% load staticfiles %}
{% load tags %}

{% get_current_language_bidi as LANGUAGE_BIDI %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="shortcut icon" href="/static/img/favicon.png" type="image/x-icon">
    <link rel="icon" href="/static/img/favicon.png" type="image/x-icon">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cadasta{% block title %}{% endblock %}</title>
    <link href="{% sass_src 'css/main.scss' %}" rel="stylesheet" type="text/css">
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'bootstrap-rtl/3.3.4/css/bootstrap-rtl.min.css' %}">
    {% endif %}
    {% include "core/tracker.html" %}
    {% block extra_head %}{% endblock %}
  </head>
  <body id="{% block top-nav %}{% endblock %}" class="page{% block body-class %}{% endblock %}">
    <div id="cadasta">
      <!-- Site header -->
      <header class="header" role="banner">
        <div class="container-fluid">
          <div id="logo" class="pull-left">
            <a href="/" aria-label="Return to home page"><img src="{% static 'img/logo-white.png' %}" alt="Return to home page" /></a>{% include "core/identifier.html" %}
          </div>
          <div class="reg-links pull-right">
            {% if user.is_authenticated %}
            <!-- User menu -->
            <div class="btn-group divider" role="group">
              <button type="button" class="btn btn-user dropdown-toggle" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
                <div class="avatar-box avatar-box-sm pull-left">
                  <img src="{{ user.avatar_url }}" alt="{{ user.name }}" class="avatar avatar-sm">
                </div>
                <span class="username visible-sm-inline visible-md-inline visible-lg-inline">{{ user.get_display_name }}</span>
                {% if is_superuser %}
                  <span class="badge" data-toggle="tooltip" data-trigger="hover" data-placement="left" title="{% trans 'You have superuser permissions' %}">SU</span>
                {% endif %}
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'account:dashboard' %}">{% trans "My dashboard" %}</a>
                </li>
                <li>
                  <a href="{% url 'account:profile' %}">{% trans "Edit profile" %}</a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <a href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                </li>
              </ul>
            </div>
            {% else %}
            <!-- New user menu -->
            <div class="divider pull-left"></div>
            <div class="btn-group" role="group">
              {% if request.path != '/account/signup/' and request.path != '/account/login/'  %}
                {% define request.path as redirect_url %}
              {% endif %}

              <a href="{% url 'account_login' %}{% if redirect_url %}?next={{ request.path }}{% endif %}" class="btn btn-reg" aria-label="Sign in">{% trans "Sign in" %}</a>
              <a href="{% url 'account_signup' %}{% if redirect_url %}?next={{ request.path }}{% endif %}" class="btn btn-reg" aria-label="Register">{% trans "Register" %}</a>
            </div>
            {% endif %}
          </div>
          <!-- Help -->
          <a class="btn btn-help pull-right visible-md-inline visible-lg-inline" aria-label="Help" id="help-link" href="#">
            <span class="glyphicon glyphicon-question-sign"></span>
          </a>
          <nav class="nav" role="navigation">
            <ul class="list-inline visible-md-block visible-lg-block">
              <li class="projects">
                <a href="{% url 'project:list' %}">
                  {% trans "Projects" %}
                </a>
              </li><!--
              --><li class="organizations">
                <a href="{% url 'organization:list' %}">
                  {% trans "Organizations" %}
                </a>
              </li>
              {% if is_superuser %}
              <li class="users">
                <a href="{% url 'user:list' %}">
                  {% trans "Users" %}
                </a>
              </li>
              {% endif %}
            </ul>
            <!-- Hamburger -->
            <div class="dropdown pull-right btn-group btn-hamburger visible-xs-inline visible-sm-inline">
              <a data-target="#" data-toggle="dropdown" class="dropdown-toggle" role="button">
                <span class="glyphicon glyphicon-menu-hamburger"></span>
              </a>
              <ul class="dropdown-menu" aria-labelledby="dLabel">
                <li class="projects"><a href="{% url 'project:list' %}">{% trans "Projects" %}</a></li>
                <li class="organizations"><a href="{% url 'organization:list' %}">{% trans "Organizations" %}</a></li>
                {% if is_superuser %}<li class="users"><a href="{% url 'user:list' %}">{% trans "Users" %}</a></li>{% endif %}
                <li role="separator" class="divider"></li>
                <li><a id="help-link" href="#"><span class="glyphicon glyphicon-question-sign"></span> {% trans "Help" %}</a></li>
              </ul>
            </div>
          </nav>
        </div>
      </header>
      <!-- /.header -->
      {% block page-header %}{% endblock %}
      <!-- Page content -->
      <div id="page-content">
        {% block sub-nav %}{% endblock %}
        <main class="container{% block main-width %}{% endblock %}" role="main">
          <div id="messages">
            {% for message in messages %}
            <div class="alert alert-dismissible{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              {{message}}
            </div>
            {% endfor %}
            <div class="alert alert-info hidden" role="alert" id="loading">
              {% trans "Loading locations..." %}
            </div>
          </div>
          <div class="row">
          {% block content %}{% endblock %}
          </div>
        </main>
      </div>
      <!-- /.page-content -->

      <!-- Site footer -->
      <footer class="footer" role="contentinfo">
        <div class="container-fluid">
          <p class="copy">
            {% now 'Y' as copydate %}
            {% blocktrans %}Copyright {{ copydate }} Cadasta. <span>All Rights Reserved.</span> {% endblocktrans %}
          </p>
          {% if not user.is_authenticated %}
          <form action="{% url 'set_language' %}" method="post" class="language">
          {% csrf_token %}
            <select id="language" class="form-control input-sm" name="language">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
              <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected="selected" {% endif %}>
                {{ language.name_local|capfirst }} ({{ language.code }})
              </option>
              {% endfor %}
            </select>
            <input hidden="true" type="submit" value="Go" />
          </form>
          {% endif %}
          <div class="footer-links">
            <ul class="list-inline">
              <li>
                <a href="http://cadasta.org/about-us/">
                  {% trans "About Us" %}
                </a>
              </li>
              <li>
                <a href="http://cadasta.org/privacy-policy/">
                  {% trans "Privacy" %}
                </a>
              </li>
              <li>
                <a href="http://cadasta.org/terms-of-use/">
                  {% trans "Terms of Use" %}
                </a>
              </li>
              <li>
                <a href="http://cadasta.org/code-of-conduct/">
                  {% trans "Code of Conduct" %}
                </a>
              </li>
              <li>
                <a href="http://github.com/Cadasta">
                  {% trans "Visit us on Github" %}
                </a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
      <!-- /.footer -->

    </div>
    {% block modals %} {% endblock %}

    <script type="text/javascript" src="{% static 'babel-polyfill/6.26.0/polyfill.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatables/1.10.8/js/datatables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dataTables.conditionalPaging.js' %}"></script>
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    <script type="text/javascript" src="{% static 'js/parsleyConfig.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/parsley.js' %}"></script>

    {% block extra_script %}{% endblock %}
    <script>
      $(document).ready(function () {
        $('.datatable').DataTable({
          conditionalPaging: true,
          "dom": '<"table-search clearfix"f>t<"table-pagination"p><"table-entries"i><"table-num"l>',
          "language": {
            "emptyTable":     "{% trans "No data available in table" %}",
            "info":           "{% trans "Showing _START_ - _END_ of _TOTAL_" %}",
            "infoEmpty":      "{% trans "Showing 0 - 0 of 0" %}",
            "infoFiltered":   "{% trans "(filtered from _MAX_ total rows)" %}",
            "lengthMenu":     '<select class="form-control input-sm">'+
                              ' <option value="10">{% trans "10 per page" %}</option>'+
                              ' <option value="25">{% trans "25 per page" %}</option>'+
                              ' <option value="50">{% trans "50 per page" %}</option>'+
                              ' <option value="100">{% trans "100 per page" %}</option>'+
                              '</select>',
            "search": '<div class="input-group"><span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>',
            "searchPlaceholder": '{% trans "Search" %}',
            "zeroRecords":    "{% trans "No matching records found" %}",
            "paginate": {
              "next": '<span class="glyphicon glyphicon-triangle-right"></span>',
              "previous": '<span class="glyphicon glyphicon-triangle-left"></span>',
              "first":      "{% trans "First" %}",
              "last":       "{% trans "Last" %}"
            },
            "aria": {
              "sortAscending":  ": {% trans "activate to sort column ascending" %}",
              "sortDescending": ": {% trans "activate to sort column descending" %}"
            }
          }
        });
        $('.dropdown-toggle').dropdown();
        $('#language').change(function() { this.form.submit(); });
        $('[data-parsley-required="true"]')
          .closest('.form-group')
            .children('label.control-label')
              .addClass('required');
      });
      window.setTimeout(function() {
        $(".alert-success")
          .fadeTo(500, 0)
          .slideUp(500, function(){
            $(this).hide();
          });
      }, 5000);
    </script>
    <script>
      // User tracking
      window.inlineManualTracking = {
        uid: "{{ user.id }}",
        username: "{{ user.username }}"
      }
    </script>
    <script type="text/javascript" src="{% static 'js/inline-manual-player.js' %}" defer></script>
  </body>
</html>

cadasta/templates/core/dashboard.html
{% extends "core/base.html" %}

{% load staticfiles %}
{% load i18n %}
{% load leaflet_tags %}

{% block top-nav %}dashboard{% endblock %}
{% block body-class %} map{% endblock %}

{% block title %} | {% trans "Dashboard" %}{% endblock %}

{% block extra_head %}
{% leaflet_css %}
<link rel="stylesheet" href="{% static 'css/MarkerCluster.css' %}">
<link rel="stylesheet" href="{% static 'css/MarkerCluster.Default.css' %}">
{% endblock %}

{% block extra_script %}
{% leaflet_js %}
<script src="{% static 'js/leaflet.markercluster.js' %}"></script>
<script src="{% static 'js/L.Map.Deflate.js' %}"></script>
<script src="{% static 'js/map_utils.js' %}"></script>
<script>
  function project_map_init(map, options) {
    var data = {{ geojson|safe }};
    map.fitBounds([[-45.0, -180.0], [45.0, 180.0]]);

    add_map_controls(map);

    var geoJson = L.geoJson(null, {
      onEachFeature: function(feature, layer) {
        layer.bindPopup("<div class=\"text-wrap\">" +
                       "<h2><span class=\"entity\">" + feature.properties.org + "</span>" +
                       feature.properties.name + "</h2></div>" +
                       "<div class=\"btn-wrap\"><a href='" + feature.properties.url + "' class=\"btn btn-primary btn-sm btn-block\">{% trans 'Open project' %}</a>"  +
                       "</div>");
      }
    });

    L.Deflate({minSize: 20, layerGroup: geoJson}).addTo(map);
    geoJson.addData(data);
  }
</script>
{% endblock %}

{% block content %}

<div class="dashboard-map">
  {% leaflet_map "dashboard-map" callback="project_map_init" %}
</div>

{% endblock %}

cadasta/templates/core/index.html
{% extends "core/base.html" %}

{% include "snippets/registration_form.html" %}