cadasta/config/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

api_v1 = [
    url(r'^account/', include('accounts.urls.api', namespace='accounts')),
    url(r'^account/', include('djoser.urls.authtoken')),

    url(r'^organizations/',
        include('organization.urls.api.organizations',
                namespace='organization')),
    url(r'^projects/',
        include('organization.urls.api.projects',
                namespace='project')),
    url(r'^users/',
        include('organization.urls.api.users',
                namespace='user')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project_id>[-\w]+)/',
        include('questionnaires.urls.api',
                namespace='questionnaires')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project>[-\w]+)/',
        include('resources.urls.api',
                namespace='resources')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project>[-\w]+)/spatial/',
        include('spatial.urls.api.spatial',
                namespace='spatial')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project>[-\w]+)/parties/',
        include('party.urls.api.parties',
                namespace='party')),
    url(r'^organizations/(?P<organization>[-\w]+)/projects/'
        '(?P<project>[-\w]+)/relationships/',
        include('party.urls.api.relationships',
                namespace='relationship')),
]

api = [
    url(r'^v1/', include(api_v1, namespace='v1'))
]

urlpatterns = [
    url(r'^',
        include('core.urls',
                namespace='core')),
    url(r'^account/',
        include('accounts.urls.default',
                namespace='account')),
    url(r'^account/',
        include('allauth.urls')),
    url('^',
        include('django.contrib.auth.urls')),
    url(r'^organizations/',
        include('organization.urls.default.organizations',
                namespace='organization')),
    url(r'^projects/',
        include('organization.urls.default.projects',
                namespace='project')),
    url(r'^users/',
        include('organization.urls.default.users',
                namespace='user')),
    url(r'^',
        include('party.urls.default',
                namespace='parties')),
    url(r'^',
        include('spatial.urls.default',
                namespace='locations')),
    url(r'^',
        include('resources.urls.default',
                namespace='resources')),

    url(r'^api/',
        include(api,
                namespace='api')),

    url(r'^i18n/',
        include('django.conf.urls.i18n')),

    url(r'', include('buckets.test.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadasta/core/urls.py
from django.conf.urls import url

from core.views import default

urlpatterns = [
    url(r'^$', default.IndexPage.as_view(), name='index'),
    url(r'^dashboard/$', default.Dashboard.as_view(), name='dashboard'),
]

cadasta/organization/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.OrganizationList.as_view(),
        name='list'),
    url(
        r'^(?P<slug>[-\w]+)/$',
        views.OrganizationDetail.as_view(),
        name='detail'),
    url(
        r'^(?P<slug>[-\w]+)/users/$',
        views.OrganizationUsers.as_view(),
        name='users'),
    url(
        r'^(?P<slug>[-\w]+)/users/(?P<username>[-\w]+)/$',
        views.OrganizationUsersDetail.as_view(),
        name='users_detail'),
    url(
        r'^(?P<slug>[-\w]+)/projects/$',
        views.ProjectList.as_view(),
        name='project_list'),
    url(
        r'^(?P<slug>[-\w]+)/projects/(?P<project_id>[-\w]+)/users/$',
        views.ProjectUsers.as_view(),
        name='project_users'),
    url(
        r'^(?P<slug>[-\w]+)/projects/(?P<project_id>[-\w]+)/users/(?P<username>[-\w]+)/$',
        views.ProjectUsersDetail.as_view(),
        name='project_users_detail'),
]

cadasta/organization/forms.py
import mimetypes

from accounts.models import User
from buckets.widgets import S3FileUploadWidget
from core.form_mixins import SanitizeFieldsForm
from core.util import slugify
from core.messages import SANITIZE_ERROR
from django import forms
from django.conf import settings
from django.contrib.gis import forms as gisforms
from django.contrib.postgres import forms as pg_forms
from django.db import transaction
from django.forms import ValidationError
from django.forms.utils import ErrorDict
from django.utils.translation import ugettext as _
from django.shortcuts import get_object_or_404
from leaflet.forms.widgets import LeafletWidget
from questionnaires.models import Questionnaire
from tutelary.models import check_perms

from .choices import ADMIN_CHOICES, ROLE_CHOICES
from organization import fields as org_fields
from .models import Organization, OrganizationRole, Project, ProjectRole

FORM_CHOICES = (('Pb', _('Public User')),) + ROLE_CHOICES
QUESTIONNAIRE_TYPES = [
    'application/msexcel',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
]


def create_update_or_delete_project_role(project, user, role):
    if role != 'Pb':
        ProjectRole.objects.update_or_create(
            user=user,
            project_id=project,
            defaults={'role': role})
    else:
        ProjectRole.objects.filter(user=user,
                                   project_id=project).delete()


class ContactsForm(SanitizeFieldsForm, forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'data-parsley-sanitize': '1'}))
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'data-parsley-sanitize': '1'}),
        required=False)
    tel = forms.CharField(
        widget=forms.TextInput(attrs={'data-parsley-sanitize': '1'}),
        required=False)
    remove = forms.BooleanField(required=False, widget=forms.HiddenInput())

    def as_table(self):
        html = self._html_output(
            normal_row='<td>%(field)s%(help_text)s</td>',
            error_row=('<tr class="contacts-error {error_types}">'
                       '<td colspan="4">%s</td></tr>\n<tr>'),
            row_ender='</td>',
            help_text_html='<br /><span class="helptext">%s</span>',
            errors_on_separate_row=False)
        closeBtn = ('<td><a data-prefix="' + self.prefix + '" '
                    'class="close remove-contact" href="#">'
                    '<span aria-hidden="true">&times;</span></a></td>')
        html = ('' if self.errors else '<tr>') + html + closeBtn + '</tr>\n'

        error_types = ''
        if 'name' in self.errors:
            error_types += ' error-name'
        if 'email' in self.errors:
            error_types += ' error-email'
        if hasattr(self, 'contact_details_is_missing'):
            error_types += ' error-email error-phone'

        return html.format(error_types=error_types)

    def full_clean(self):
        if self.data.get(self.prefix + '-remove') != 'on':
            super().full_clean()
        else:
            self._errors = ErrorDict()
            self.cleaned_data = {'remove': True}

    def clean(self):
        cleaned_data = super().clean()
        error_msgs = []

        if 'name' in self.errors:
            if not self.data.get(self.prefix + '-name'):
                error_msgs.append(_("Please provide a name."))
            else:
                error_msgs.append(SANITIZE_ERROR)
        if 'email' in self.errors:
            error_msgs.append(_("The provided email address is invalid."))
        if (
            not self.errors and
            not cleaned_data['email'] and
            not cleaned_data['tel']
        ):
            self.contact_details_is_missing = True
            error_msgs.append(_(
                "Please provide either an email address or a phone number."))
        if error_msgs:
            raise forms.ValidationError(" ".join(error_msgs))

        return cleaned_data

    def clean_string(self, value):
        if not value:
            return None
        return value

    def clean_email(self):
        return self.clean_string(self.cleaned_data['email'])

    def clean_tel(self):
        return self.clean_string(self.cleaned_data['tel'])


class OrganizationForm(SanitizeFieldsForm, forms.ModelForm):
    urls = pg_forms.SimpleArrayField(
        forms.URLField(required=False),
        required=False,
        error_messages={'item_invalid': ""},
    )
    contacts = org_fields.ContactsField(form=ContactsForm, required=False)
    access = org_fields.PublicPrivateField()

    class Meta:
        model = Organization
        fields = ['name', 'description', 'urls', 'contacts', 'access']

    class Media:
        js = ('js/file-upload.js', 'js/sanitize.js')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['name'].error_messages['unique'] = _(
            "Organization with this name already exists.")

    def clean_name(self):
        name = self.cleaned_data['name']
        invalid_names = settings.CADASTA_INVALID_ENTITY_NAMES
        if slugify(name, allow_unicode=True) in invalid_names:
            raise forms.ValidationError(
                _("Organization name cannot be “Add” or “New”."))

        is_create = not self.instance.id
        queryset = Organization.objects.filter(name__iexact=name)
        if is_create:
            not_unique = queryset.exists()
        else:
            not_unique = queryset.exclude(id=self.instance.id).exists()
        if not_unique:
            raise forms.ValidationError(
                self.fields['name'].error_messages['unique'])

        return name

    def save(self, *args, **kwargs):
        instance = super().save(commit=False)
        is_create = not instance.id

        instance.save()

        if is_create:
            OrganizationRole.objects.create(
                organization=instance,
                user=self.user,
                admin=True
            )

        return instance


class AddOrganizationMemberForm(forms.Form):
    identifier = forms.CharField()

    def __init__(self, *args, **kwargs):
        self.organization = kwargs.pop('organization', None)
        self.instance = kwargs.pop('instance', None)
        super(AddOrganizationMemberForm, self).__init__(*args, **kwargs)

    def clean_identifier(self):
        identifier = self.data.get('identifier')
        try:
            self.user = User.objects.get_from_username_or_email_or_phone(
                identifier=identifier)
        except (User.DoesNotExist, User.MultipleObjectsReturned) as e:
            raise forms.ValidationError(e)
        user_exists = OrganizationRole.objects.filter(
            user=self.user, organization=self.organization).exists()
        if user_exists:
            raise forms.ValidationError(
                _("User is already a member of the organization."),
                code='member_already')

    def save(self):
        if self.errors:
            raise ValueError(
                _("The role could not be assigned because the data didn't "
                  "validate.")
            )

        self.instance = OrganizationRole.objects.create(
            organization=self.organization, user=self.user)
        return self.instance


class EditOrganizationMemberForm(forms.Form):
    org_role = forms.ChoiceField(choices=ADMIN_CHOICES)

    def __init__(self, org, user, current_user, data=None, *args, **kwargs):
        super(EditOrganizationMemberForm, self).__init__(data, *args, **kwargs)
        self.data = data
        self.organization = org
        self.user = user
        self.current_user = current_user

        self.org_role_instance = get_object_or_404(
            OrganizationRole,
            user=user,
            organization=self.organization)

        self.initial['org_role'] = 'A' if self.org_role_instance.admin else 'M'

    def clean_org_role(self):
        org_role = self.cleaned_data['org_role']
        if (self.org_role_instance.admin and
                self.current_user == self.user and
                not self.user.is_superuser):
            if self.data.get('org_role') != 'A':
                raise forms.ValidationError(
                    _("Organization administrators cannot change their own" +
                        " role in the organization."))
        return org_role

    def save(self):
        self.org_role_instance.admin = self.data.get('org_role') == 'A'
        self.org_role_instance.save()


class EditOrganizationMemberProjectPermissionForm(forms.Form):

    def __init__(self, org, user, current_user, data=None, *args, **kwargs):
        super(EditOrganizationMemberProjectPermissionForm, self).__init__(
            data, *args, **kwargs)
        self.data = data
        self.organization = org
        self.user = user
        self.current_user = current_user
        self.org_role_instance = OrganizationRole.objects.get(
            user=user, organization=self.organization)

        project_roles = ProjectRole.objects.filter(
            user=user, project__organization=org).values('project__id', 'role')
        project_roles = {r['project__id']: r['role'] for r in project_roles}
        active_projects = self.organization.projects.filter(archived=False)

        admin = self.org_role_instance.admin or user.is_superuser

        for p in active_projects.values_list('id', 'name'):
            role = project_roles.get(p[0], 'Pb')
            self.fields[p[0]] = org_fields.ProjectRoleEditField(
                choices=FORM_CHOICES,
                label=p[1],
                required=(not admin),
                initial=role,
                admin=admin,
            )

    def save(self):
        for f in [field for field in self.fields]:
            role = self.data.get(f)
            create_update_or_delete_project_role(f, self.user, role)


class ProjectAddExtents(forms.ModelForm):

cadasta/organization/views/async.py
from django.core.urlresolvers import reverse
from core.mixins import PermissionRequiredMixin
import core.views.generic as generic

from . import mixins
from .. import messages as error_messages
from ..models import Project


class ProjectDashboard(PermissionRequiredMixin,
                       mixins.ProjectAdminCheckMixin,
                       mixins.ProjectMixin,
                       generic.DetailView):

    def get_actions(self, view):
        if self.prj.archived:
            return 'project.view_archived'
        if self.prj.public():
            return 'project.view'
        else:
            return 'project.view_private'

    model = Project
    template_name = 'organization/project_dashboard.html'
    permission_required = {'GET': get_actions}
    permission_denied_message = error_messages.PROJ_VIEW

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        num_locations = self.object.spatial_units.count()
        num_parties = self.object.parties.count()
        num_resources = self.object.resource_set.filter(
            archived=False).count()
        context['has_content'] = (
            num_locations > 0 or num_parties > 0 or num_resources > 0)
        context['num_locations'] = num_locations
        context['num_parties'] = num_parties
        context['num_resources'] = num_resources
        context['success_url'] = reverse('organization:project-dashboard',
                                         kwargs=self.kwargs)

        return context

    def get_object(self, queryset=None):
        return self.get_project()

cadasta/templates/organization/organization_add.html
{% extends "organization/organization_list.html" %}

{% load i18n %}
{% load staticfiles %}

{% block title %} | {% trans "Add organization" %}{% endblock %}

{% block modals %}

<div class="modal-backdrop">
  <div class="modal show" data-backdrop="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <form method="POST"
              action="{% url 'organization:add' %}" class="modal-organization-add" data-parsley-validate>
          <div class="modal-header">
            <a class="close" href="{% url 'organization:list' %}">
              <span aria-hidden="true">&times;</span>
            </a>
            <h3 class="modal-title">{% trans "Add organization" %}</h3>
          </div>
          <div class="modal-body">
            {% include "organization/organization_form.html" %}
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary pull-right" name="submit">
              {% trans "Save" %}
            </button>
            <a class="btn btn-link cancel" href="{% url 'organization:list' %}">
              {% trans "Cancel" %}
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block extra_script %}
  {{ form.media }}
{% endblock %}

cadasta/templates/organization/organization_edit.html
{% extends "organization/organization_dashboard.html" %}

{% load i18n %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block title %} | {% trans "Edit" %} {{ form.instance.name }}{% endblock %}

{% block modals %}

<div class="modal-backdrop">
  <div class="modal show" data-backdrop="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <form method="POST"
              action="{% url 'organization:edit' form.instance.slug %}" class="edit-org" data-parsley-validate>
          <div class="modal-header">
            <a class="close" href="{% url 'organization:dashboard' form.instance.slug %}">
              <span aria-hidden="true">&times;</span>
            </a>
            <h3 class="modal-title">{% trans "Edit organization" %}</h3>
          </div>
          <div class="modal-body">
            {% include "organization/organization_form.html" %}
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary pull-right" name="submit">
              {% trans "Save" %}
            </button>
            <a class="btn btn-link cancel"
               href="{% url 'organization:dashboard' form.instance.slug %}">
              {% trans "Cancel" %}
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block extra_script %}
  {{ form.media }}
{% endblock %}

cadasta/templates/organization/organization_form.html
{% load i18n %}
{% load widget_tweaks %}

{% csrf_token %}

{{ form.non_field_errors }}

<div class="row">
  <div class="col-sm-12">
    <div class="form-group{% if form.name.errors %} has-error{% endif %}">
      <label class="control-label" for="{{ form.name.id_for_label }}">{% trans "Organization name" %}</label>
      {% render_field form.name class+="form-control" data-parsley-required="true" data-parsley-sanitize="1" %}
      <div class="error-block">{{ form.name.errors }}</div>
    </div>
  </div>
  <!-- <div class="col-sm-4">
    {{ form.access }}
  </div> -->
</div>

<div class="form-group{% if form.description.errors %} has-error{% endif %}">
  <label class="control-label" for="{{ form.description.id_for_label }}">{% trans "Organization description" %}</label>
  {% render_field form.description class+="form-control" data-parsley-sanitize="1" %}
  <div class="error-block">{{ form.description.errors }}</div>
</div>

<div class="form-group{% if form.urls.errors %} has-error{% endif %}">
  <label class="control-label" for="{{ form.urls.id_for_label }}">{% trans "Organization URL" %}</label>
  {% render_field form.urls class+="form-control" placeholder="http://" data-parsley-type="url" %}
  <div class="error-block">{{ form.urls.errors }}</div>
</div>

<label>{% trans "Contacts" %}</label>
{% render_field form.contacts class+="form-control" %}

cadasta/templates/organization/project_wrapper.html
{% extends "core/base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block top-nav %}project-single{% endblock %}

{% block title %} | {% block page_title %}{% endblock %} {{ object.name }}{% endblock %}

{% block main-width %}-fluid{% if is_project_member %} show-sidebar{% endif %}{% endblock %}

{% block page-header %}
<!-- Single project header -->
<div class="header page-header">
  <div class="page-title">
    <h1 class="{% if is_administrator or is_allowed_add_location or is_allowed_add_resource %}short{% endif %}">
      <a href="{% url 'organization:dashboard' slug=object.organization.slug %}" class="org-name">{{ object.organization.name }}</a>
      {{ object.name }}
      {% if object.access == "private" %}
        <span class="label label-info">{% trans "Private" %}</span>
      {% endif %}
      {% if object.archived %}
        <span class="label label-danger">{% trans "Archived" %}</span>
      {% endif %}
    </h1>
    <div class="top-btn">

      <!-- Project translation dropdown-->
      {% if form_langs and is_project_member %}
      <div class="langs-select form-group pull-right">
        <label class="control-label sr-only" for="form-langs-select">{% trans "Language for project fields" %}</label>
        <select id="form-langs-select" class="form-control" data-project-slug="{{ object.slug }}" data-default-lang="{{ form_lang_default }}">
          {% for lang in form_langs %}
          <option value="{{ lang.0 }}" {% if lang.0 == form_lang_default %}selected{% endif %}>{{ lang.1 }}</option>
          {% endfor %}
        </select>
      </div>
      {% endif %}

      <!-- More actions menu -->
      {% if is_administrator %}
        <div class="dropdown pull-right btn-add">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-label="{% trans 'More actions' %}" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dLabel">
            <li><a class="edit" href="{% url 'organization:project-edit-geometry' object.organization.slug object.slug %}">{% trans "Edit project boundary" %}</a></li>
            <li><a class="edit" href="{% url 'organization:project-edit-details' object.organization.slug object.slug %}">{% trans "Edit project details" %}</a></li>
            <li><a class="edit" href="{% url 'organization:project-edit-permissions' object.organization.slug object.slug %}">{% trans "Edit member permissions" %}</a></li>
            {% if is_superuser %}<li><a class="edit" href="{% url 'organization:project-detach' object.organization.slug object.slug %}">Detach spatial resources</a></li>{% endif %}

            <li role="separator" class="divider"></li>
            <li><a href="{% url 'organization:project-import' object.organization.slug object.slug %}" data-toggle="modal">{% trans "Import data" %}</a></li>
            <li><a href="{% url 'organization:project-download' object.organization.slug object.slug %}" data-toggle="modal">{% trans "Export data" %}</a></li>
            <li role="separator" class="divider"></li>
            <li>
              {% if object.archived %}
              <a class="archive" href="#unarchive_confirm" data-toggle="modal">{% trans "Unarchive project" %}</a>
              {% else %}
              <a class="archive" href="#archive_confirm" data-toggle="modal">{% trans "Archive project" %}</a>
              {% endif %}
            </li>
          </ul>
        </div>
      {% endif %}

      <!-- Add locations menu -->
      <div class="btn-group pull-right btn-add visible-sm-inline visible-md-inline visible-lg-block">
        {% if is_allowed_add_location %}
          <a class="btn btn-primary" href="{% url 'locations:add' object.organization.slug object.slug %}" aria-label="{% trans 'Add location' %}">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> {% trans "Add location" %}
          </a>
        {% endif %}
        {% if is_allowed_add_resource or is_allowed_import %}
          <button type="button" class="btn btn-primary btn-rt dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">{% trans "Toggle add" %}</span>
          </button>
          <ul class="dropdown-menu">
            {% if is_allowed_add_party %}<li><a href="{% url 'parties:add' object.organization.slug object.slug %}">{% trans "Add party" %}</a></li>{% endif %}
            {% if is_allowed_add_resource %}<li><a href="{% url 'resources:project_add_new' object.organization.slug object.slug %}">{% trans "Add resource" %}</a></li>{% endif %}
            {% if is_allowed_add_resource and is_allowed_import %}<li role="separator" class="divider"></li>{% endif %}
            {% if is_allowed_import %}<li><a href="{% url 'organization:project-import' object.organization.slug object.slug %}" data-toggle="modal">{% trans "Import data" %}</a></li>{% endif %}
          </ul>
        {% endif %}
      </div>

      <!-- Single add button for smaller screens-->
      <div class="dropdown pull-right visible-xs-inline">
        {% if is_allowed_add_location or is_allowed_add_resource %}
        <a data-target="#" data-toggle="dropdown" class="btn btn-primary btn-add dropdown-toggle" role="button" aria-label="{% trans 'Add location' %}">
          <span class="glyphicon glyphicon-plus"></span>
        </a>
        <ul class="dropdown-menu" aria-labelledby="dLabel">
          {% if is_allowed_add_location %}
          <li><a href="{% url 'locations:add' object.organization.slug object.slug %}">{% trans "Add location" %}</a></li>
          {% endif %}
          {% if is_allowed_add_party %}
          <li><a href="{% url 'parties:add' object.organization.slug object.slug %}">{% trans "Add party" %}</a></li>
          {% endif %}
          {% if is_allowed_add_resource %}
          <li><a href="{% url 'resources:project_add_existing' object.organization.slug object.slug %}">{% trans "Add resource" %}</a></li>
          {% endif %}
          <li role="separator" class="divider"></li>
          <li><a href="{% url 'organization:project-import' object.organization.slug object.slug %}" data-toggle="modal">{% trans "Import data" %}</a></li>
        </ul>
        {% endif %}
      </div>

    </div>
  </div>
</div>
<!-- / single project header -->
{% endblock %}

{% block extra_script %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/xlang.js' %}"></script>
{% endblock %}

{% block sub-nav %}
{% if is_project_member %}
<!-- Sidebar -->
<div id="sidebar" class="{% block left-nav %}{% endblock %}">
  <ul class="nav nav-sidebar">
    <li class="search">
      <a href="#">
        <span class="icon"></span>
        <span class="title">{% trans "Search" %}</span>
      </a>
    </li><!-- needed to eliminate spacing issue on horizontal menus
    --><li class="dashboard">
      <a href="{% url 'organization:project-dashboard' object.organization.slug object.slug %}">
        <span class="icon"></span>
        <span class="title">{% trans "Dashboard" %}</span>
      </a>
    </li><!--
    --><li class="map">
      <a href="{% url 'locations:list' object.organization.slug object.slug %}">
        <span class="icon map"></span>
        <span class="title">{% trans "Data" %}</span>
      </a>
    </li><!--
    --><li class="parties">
      <a href="{% url 'parties:list' object.organization.slug object.slug %}">
        <span class="icon parties"></span>
        <span class="title">{% trans "Parties" %}</span>
      </a>
    </li><!--
    --><li class="resources">
      <a href="{% url 'resources:project_list' object.organization.slug object.slug %}">
        <span class="icon resources"></span>
        <span class="title">{% trans "Resources" %}</span>
      </a>
    </li>
  </ul>
</div>
<!-- /.sidebar -->
<!-- Sidebar search box-->
<div id="sidebar-search-box" class="disabled" data-search-url="{% url 'search:search' object.organization.slug object.slug %}">
  <form action="#" class="form-inline">
    <div class="form-group">
      <label class="control-label sr-only">{% trans "Search within project for" %}</label>
      <input type="text" class="form-control pull-left" placeholder="{% trans 'Search within project' %}" value="">
      <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    </div>
  </form>
</div>
<script>
'use strict';
window.addEventListener('load', function() {
  $( '.search').find('.search').click( function(){
   $('.content-single').animate({ scrollTop: 0 }, 'fast');
  });
  $('#sidebar .nav-sidebar .search a').bind('click', function(e) {
    if (!$('#sidebar').hasClass('search')) {
      if ($('#sidebar-search-box').hasClass('disabled')) {
        $('#sidebar-search-box').removeClass('disabled');
        $('#sidebar-search-box input').focus();
      } else {
        $('#sidebar-search-box').addClass('disabled');
      }
    }
  });
  $('#sidebar-search-box form').bind('submit', function(e) {
    var query = $('#sidebar-search-box input')[0].value;
    var url = $('#sidebar-search-box')[0].dataset.searchUrl + '?q=' + encodeURIComponent(query);
    window.location = url;
    return false;
  });
});
</script>
<!-- /.sidebar search box -->
{% endif %}
{% endblock %}

{% block content %}{% endblock %}

{% block modals %}
{% if is_project_member %}
{% block form_modal %}{% endblock %}
<div class="modal fade" id="archive_confirm" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title">{% trans "Archive project" %}</h3>
      </div>
      <div class="modal-body">
        <p>{% trans "Are you sure you want to archive this project?" %}</p>
      </div>
      <div class="modal-footer">
        <a href="{% url 'organization:project-archive' object.organization.slug object.slug %}" class="btn btn-danger archive-final pull-right" role="button">
          {% trans "Yes, archive this project" %}
        </a>
        <button type="button" class="btn btn-link cancel" data-dismiss="modal">
          {% trans "Cancel" %}
        </button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="unarchive_confirm" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title">{% trans "Unarchive project" %}</h3>
      </div>
      <div class="modal-body">
        <p>
          {% trans "Are you sure you want to unarchive this project?" %}
        </p>
      </div>
      <div class="modal-footer">
        <a href="{% url 'organization:project-unarchive' object.organization.slug object.slug %}" class="btn btn-primary unarchive-final pull-right" role="button">
          {% trans "Yes, unarchive this project" %}
        </a>
        <button type="button" class="btn btn-link cancel cancel-u" data-dismiss="modal">
          {% trans "Cancel" %}
        </button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endif %}
{% endblock %}